PS C:\Users\TM MUNGOMENI\Documents\Websites\VSX~changeZA web\backend> python seed_user.py
Traceback (most recent call last):
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute  
    cursor.execute(statement, parameters)       
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^       
sqlite3.IntegrityError: NOT NULL constraint failed: users.password_hash

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TM MUNGOMENI\Documents\Websites\VSX~changeZA web\backend\seed_user.py", line 25, in <module>
    db.commit()
    ~~~~~~~~~^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit        
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go      
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit        
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl     
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go      
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl 
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush        
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__  
    raise exc_value.with_traceback(exc_tb)      
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush        
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute     
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute     
    util.preloaded.orm_persistence.save_obj(    
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^    
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj    
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,    
    )
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute       
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,        
    )
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(   
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^   
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters 
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute  
    cursor.execute(statement, parameters)       
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^       
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: users.password_hash
[SQL: INSERT INTO users (first_name, last_name, email, password_hash, role, location, bio, discoverable) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]       
[parameters: ('Test', 'User', 'test@example.com', None, 'Developer', 'Limpopo', None, 1)]       
(Background on this error at: https://sqlalche.me/e/20/gkpj)
PS C:\Users\TM MUNGOMENI\Documents\Websites\VSX~changeZA web\backend> .venv\Scripts\activate
.venv\Scripts\activate : File C:\Users\TM 
MUNGOMENI\Documents\Websites\VSX~changeZA       
web\backend\.venv\Scripts\Activate.ps1 cannot   
be loaded because running scripts is disabled   
on this system. For more information, see       
about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.  
At line:1 char:1
+ .venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (  
   :) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAcce  
   ss
PS C:\Users\TM MUNGOMENI\Documents\Websites\VSX~changeZA web\backend> python seed_user.py
Traceback (most recent call last):
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute  
    cursor.execute(statement, parameters)       
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^       
sqlite3.IntegrityError: NOT NULL constraint failed: users.password_hash

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TM MUNGOMENI\Documents\Websites\VSX~changeZA web\backend\seed_user.py", line 25, in <module>
    db.commit()
    ~~~~~~~~~^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit        
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go      
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit        
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl     
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go      
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl 
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush        
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__  
    raise exc_value.with_traceback(exc_tb)      
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush        
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute     
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute     
    util.preloaded.orm_persistence.save_obj(    
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^    
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj    
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,    
    )
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute       
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,        
    )
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(   
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^   
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters 
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\TM MUNGOMENI\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute  
    cursor.execute(statement, parameters)       
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^       
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: users.password_hash
[SQL: INSERT INTO users (first_name, last_name, email, password_hash, role, location, bio, discoverable) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]       
[parameters: ('Test', 'User', 'test@example.com', None, 'Developer', 'Limpopo', None, 1)]       
(Background on this error at: https://sqlalche.me/e/20/gkpj)
